name: dsqm
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  analyzer: ^5.13.0
  analyzer_plugin: ^0.11.2
  args: ^2.4.1
  collection: ^1.17.2
  file: ^7.0.0
  glob: ^2.1.2
  mockito: ^5.4.1
  path: ^1.8.3
  source_span: ^1.10.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
